[workspace]
resolver = "2"
members = [
    # binary crates
    "crates/minecrium_main",

    # library crates
]


[workspace.package]
authors = ["HYF"]
edition = "2021"
version = "0.1.0"
description = "minecraft clone in rust + bevy"
categories = ["games"]
keywords = ["game", "minecraft"]
readme = "README.md"
repository = "https://github.com/HyfLink/minecrium"
homepage = "https://github.com/HyfLink/minecrium"
license = "Apache-2.0"
license-file = "LICENSE.txt"


[workspace.dependencies]
# dependencies.proc-macro
proc-macro2 = { version = "1.0" }
quote = { version = "1.0" }
syn = { version = "2.0" }
# dependencies.other
bevy = { version = "0.10.0", features = ["dynamic_linking", "serialize"] }
rand = { version = "0.8", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }


[workspace.metadata]
