[workspace]

resolver = "2"
members = [
    # binary crates
    "crates/minecrium_main",

    # library crates
]

[workspace.package]
authors = ["HYF"]
edition = "2021"
version = "0.1.0"
description = "minecraft clone in rust + bevy"
categories = ["games"]
keywords = ["game", "minecraft"]
readme = "README.md"
repository = "https://github.com/HyfLink/minecrium"
homepage = "https://github.com/HyfLink/minecrium"
license = "Apache-2.0"
license-file = "LICENSE.txt"

[workspace.dependencies]

[workspace.metadata]
