[package]
name = "minecrium_main"
description = "the minecrium executable"

authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
